config/routes.rb
Rails.application.routes.draw do
  resources :astronomia

end

app/models/astronomium.rb
class Astronomium < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/astronomia_controller.rb
class AstronomiaController < ApplicationController
  before_action :set_astronomium, only: [:show, :edit, :update, :destroy]

  # GET /astronomia
  # GET /astronomia.json
  def index
    @astronomia = Astronomium.all
  end

  # GET /astronomia/1
  # GET /astronomia/1.json
  def show
  end

  # GET /astronomia/new
  def new
    @astronomium = Astronomium.new
  end

  # GET /astronomia/1/edit
  def edit
  end

  # POST /astronomia
  # POST /astronomia.json
  def create
    @astronomium = Astronomium.new(astronomium_params)

    respond_to do |format|
      if @astronomium.save
        format.html { redirect_to @astronomium, notice: 'Registro Creado con Exito.' }
        format.json { render :show, status: :created, location: @astronomium }
      else
        format.html { render :new }
        format.json { render json: @astronomium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /astronomia/1
  # PATCH/PUT /astronomia/1.json
  def update
    respond_to do |format|
      if @astronomium.update(astronomium_params)
        format.html { redirect_to @astronomium, notice: 'Registro Actualizado con Exito.' }
        format.json { render :show, status: :ok, location: @astronomium }
      else
        format.html { render :edit }
        format.json { render json: @astronomium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /astronomia/1
  # DELETE /astronomia/1.json
  def destroy
    @astronomium.destroy
    respond_to do |format|
      format.html { redirect_to astronomia_url, notice: 'Registro Eliminado con Exito.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_astronomium
      @astronomium = Astronomium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def astronomium_params
      params.require(:astronomium).permit(:Nombre, :Categoria, :Descripcion)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/astronomia_helper.rb
module AstronomiaHelper
end

app/views/astronomia/_form.html.erb
<%= form_for(@astronomium) do |f| %>
  <% if @astronomium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@astronomium.errors.count, "error") %> prohibited this astronomium from being saved:</h2>

      <ul>
      <% @astronomium.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Categoria %><br>
    <%= f.text_field :Categoria %>
  </div>
  <div class="field">
    <%= f.label :Descripcion %><br>
    <%= f.text_field :Descripcion %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/astronomia/edit.html.erb
<h1>Editando Registro</h1>

<%= render 'form' %>

<%= link_to 'Ver', @astronomium %> |
<%= link_to 'Volver', astronomia_path %>

app/views/astronomia/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Registros Astronomia</h1>

<table class="table">
  <thead class="thead-inverse">
    <tr>
        <th>Nombre</th>
      <th>Categoria</th>
      <th>Descripción</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @astronomia.each do |astronomium| %>
      <tr>
        <td><%= astronomium.Nombre %></td>
        <td><%= astronomium.Categoria %></td>
        <td><%= astronomium.Descripcion %></td>
        <td><%= link_to 'Ver', astronomium %></td>
        <td><%= link_to 'Editar', edit_astronomium_path(astronomium) %></td>
        <td><%= link_to 'Eliminar', astronomium, method: :delete, data: { confirmacion: 'Está seguro de eliminar?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Registro', new_astronomium_path %>
</div>

app/views/astronomia/new.html.erb
<h1>Nuevo Registro</h1>

<%= render 'form' %>

<%= link_to 'Volver', astronomia_path %>

app/views/astronomia/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @astronomium.Nombre %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @astronomium.Categoria %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @astronomium.Descripcion %>
</p>

<%= link_to 'Editar', edit_astronomium_path(@astronomium) %> |
<%= link_to 'Volver', astronomia_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<div class="container">
<head>
  <title>Examen</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

</body>
</html>
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://blackrockdigital.github.io/startbootstrap-new-age/vendor/bootstrap/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  </head>
  <body>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<%= yield %>
  </body>
</div>
</html>